title: Adrian Kahali's Technical Writing Portfolio
description: Adrian Kahali's Technical Writing Portfolio
theme: just-the-docs

url: https://drink-rain.github.io/portfolio

aux_links:
  Template Repository: https://github.com/drink-rain/portfolio
