title: Adrian Kahali's Portfolio
description: Adrian Kahali's Technical Writing Portfolio
theme: just-the-docs

url: https://drink-rain.github.io/portfolio

aux_links:
  Template Repository: https://github.com/drink-rain/portfolio

sesrch_enabled: false

callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: purple
  info:
    title: Info
    color: blue