title: Adrian Kahali
description: Adrian Kahali's Technical Writing Portfolio
theme: just-the-docs

url: adriankahali.com

aux_links:
  Resume: /portfolio/Adrian Kahali - Resume.pdf
  LinkedIn: https://www.linkedin.com/in/adrian-kahali-783897301/
  Source on GitHub: https://github.com/drink-rain/portfolio

aux_links_new_tab: true

search_enabled: false

callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: purple
  info:
    title: Info
    color: blue